// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var UHExp$Extraction = require("../UHExp.bs.js");

console.log(UHExp$Extraction.string_of_operator(/* Space */0));

/*  Not a pure module */
