// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function uhpat_operand(t) {
  return t[1][0];
}

function uhtyp_opseq_operand(op) {
  return op[1][0];
}

var uhtyp_operand = uhtyp_opseq_operand;

exports.uhpat_operand = uhpat_operand;
exports.uhtyp_opseq_operand = uhtyp_opseq_operand;
exports.uhtyp_operand = uhtyp_operand;
/* No side effect */
