// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function opseq_operand_uhpat(t) {
  return t[1][0];
}

function opseq_operand_uhtyp(t) {
  return t[1][0];
}

exports.opseq_operand_uhpat = opseq_operand_uhpat;
exports.opseq_operand_uhtyp = opseq_operand_uhtyp;
/* No side effect */
