// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function is_Let(param) {
  return $$String.equal("let", param);
}

function is_Case(param) {
  return $$String.equal("case", param);
}

function mk(text) {
  if ($$String.equal("let", text)) {
    return /* Let */0;
  } else if ($$String.equal("case", text)) {
    return /* Case */1;
  } else {
    return ;
  }
}

function to_string(param) {
  if (param) {
    return "case";
  } else {
    return "let";
  }
}

exports.is_Let = is_Let;
exports.is_Case = is_Case;
exports.mk = mk;
exports.to_string = to_string;
/* No side effect */
