// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function to_var(kw) {
  if (kw) {
    return "case";
  } else {
    return "let";
  }
}

exports.to_var = to_var;
/* No side effect */
