// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function next(x) {
  var n = x + 1 | 0;
  return /* tuple */[
          x,
          n
        ];
}

var init = 0;

exports.init = init;
exports.next = next;
/* No side effect */
