// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function map(f, opt) {
  if (opt !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(opt)));
  }
  
}

function map2(f, opt1, opt2) {
  if (opt1 !== undefined && opt2 !== undefined) {
    return Caml_option.some(Curry._2(f, Caml_option.valFromOption(opt1), Caml_option.valFromOption(opt2)));
  }
  
}

function map_default($$default, f, opt) {
  if (opt !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(opt));
  } else {
    return $$default;
  }
}

function get(if_absent, opt) {
  if (opt !== undefined) {
    return Caml_option.valFromOption(opt);
  } else {
    return Curry._1(if_absent, /* () */0);
  }
}

function test(opt) {
  return opt !== undefined;
}

exports.map = map;
exports.map2 = map2;
exports.map_default = map_default;
exports.get = get;
exports.test = test;
/* No side effect */
