// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var SkelInconsistentWithOpSeq = Caml_exceptions.create("UHTyp-Extraction.SkelInconsistentWithOpSeq");

exports.SkelInconsistentWithOpSeq = SkelInconsistentWithOpSeq;
/* No side effect */
