// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var lamSym = "\xce\xbb";

var caseArrowSym = "\xe2\x87\x92";

var typeArrowSym = "\xe2\x86\x92";

var typeN = "\xe2\x84\x95";

var typeB = "\xf0\x9d\x94\xb9";

var user_newline = "\xe2\x86\xb5";

var nbsp = "\xc2\xa0";

var zwsp = "\xe2\x80\x8b";

exports.lamSym = lamSym;
exports.caseArrowSym = caseArrowSym;
exports.typeArrowSym = typeArrowSym;
exports.typeN = typeN;
exports.typeB = typeB;
exports.user_newline = user_newline;
exports.nbsp = nbsp;
exports.zwsp = zwsp;
/* No side effect */
