// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function length(prim) {
  return prim.length;
}

var eq = $$String.equal;

exports.eq = eq;
exports.length = length;
/* No side effect */
